# Generated by Django 4.1.4 on 2022-12-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'transacoes'},
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='obsevacoes',
            new_name='observacoes',
        ),
    ]
